// Lista de todos os projetos exibidos na seção "Meus Projetos"
// Formato: [nome, ano, tipo, tags[], imagem, link]
const PROJETOS = [
  [
    "devero",
    "2026",
    "Freelance",
    ["Landing Page", "UI", "tailwindcss", "javascript", "html", "css", "gsap", "scrolltrigger"],
    "./assets/images/devero.webp",
    "https://www.linkedin.com/feed/update/urn:li:activity:7442203757192548352/",
  ],
  [
    "museu",
    "2026",
    "Completo",
    ["WebGL", "Three.js", "3D", "javascript", "gsap", "scrolltrigger", "interatividade"],
    "./assets/images/Captura de Tela (2).webp",
    "https://museupedroca.vercel.app/",
  ],
  [
    "fjstopografia",
    "2026",
    "Freelance",
    ["Site", "Responsividade Mobile", "javascript", "html", "css", "gsap", "scrolltrigger", "three.js", "full stack", "node.js", "mongodb"],
    "./assets/images/topografia.webp",
    "https://www.fjstopografia.com.br/",
  ],
  [
    "convite de casamento",
    "2026",
    "Freelance",
    ["Design", "Front-end", "Back-end", "Full Stack", "node.js", "javascript", "three.js", "mongodb", "html", "css", "gsap", "scrolltrigger"],
    "./assets/images/valquiria.webp",
    "https://github.com/pedrogarcialeite04/landingpage-casamento",
  ],
  [
    "landing page Theze",
    "2025",
    "Freelance",
    ["Landing Page", "javascript", "html", "css", "gsap", "scrolltrigger", "three.js"],
    "./assets/images/theze.webp",
    "https://thezeagricola.netlify.app/",
  ],
  [
    "Posto",
    "2025",
    "completo",
    ["full stack", "node.js", "mongodb", "javascript"],
    "./assets/images/posto.webp",
    "https://www.youtube.com/watch?v=9zFzS9nHbZU",
  ],
  [
    "Sistema de Vendas",
    "2025",
    "Completo",
    ["full stack", "node.js", "mongodb", "javascript"],
    "./assets/images/venda.webp",
    "https://www.youtube.com/watch?v=skiS8TAx6zA",
  ],
  [
    "pg flow",
    "2025",
    "completo",
    ["Landing Page", "front-end", "javascript", "gsap", "scrolltrigger"],
    "./assets/images/pgflow.webp",
    "https://pgflow.vercel.app/",
  ],
  [
    "Registro de Gastos",
    "2025",
    "completo",
    ["full stack", "node.js", "mongodb", "javascript"],
    "./assets/images/robo.webp",
    "https://registrospedro.netlify.app/",
  ],
  [
    "foco",
    "2026",
    "completo",
    ["full stack", "UI", "javascript", "gsap"],
    "./assets/images/foco.webp",
    "https://foco-rotina.vercel.app/",
  ],
  [
    "Thegadu",
    "2026",
    "freelance",
    ["full stack", "node.js", "mongodb", "javascript"],
    "./assets/images/thegadu.webp",
    "https://thegadu.onrender.com/entrada.html",
  ],
  [
    "Registros de Cheques",
    "2026",
    "freelance",
    ["full stack", "node.js", "mongodb", "javascript"],
    "./assets/images/cheques.webp",
    "https://saa-s-cheques.vercel.app/",
  ],
  [
    "PratoUp",
    "2026",
    "freelance",
    ["Landing Page", "UI", "javascript", "html", "css", "gsap", "scrolltrigger"],
    "./assets/images/pratoup.webp",
    "https://pratoup.com.br/",
  ],
];

export { PROJETOS };
